### ISSUE TITLE
CTA Buttons not responding as expect

### ISSUE THREAD

**Issue by natintosh** [smileidentity/ios#215]
Continue button not responsive after a successful Selfie Capture likewise Close button also not responsive after a failed Selfie Capture

https://github.com/user-attachments/assets/945bc70e-1efd-4013-af60-783d92d7ba57

https://github.com/user-attachments/assets/0f80b1ed-80af-4262-a6e8-0b6d505c8c20

**Comment by tobitech** [comment]
Hello @natintosh This seems to be an issue in the Flutter SDK. You can raise issues on the flutter repo here - https://github.com/smileidentity/flutter/issues. Thanks for bringing our attention to this.

**Comment by natintosh** [comment]
Thank you. I have a major block with Smile on iOS I'll really appreciate it if I can have a sync with one of your engineers

**Comment by tobitech** [comment]
@natintosh Please use the intercom widget on the portal or send an email to technical support [support@usesmileid.com](mailto:support@usesmileid.com)
